version: 2.1

orbs:
  codacy: codacy/base@0.3.14

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: compile_test
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test"
            sbt ++2.11.12 test
            sbt ++2.12.10 test
            sbt ++2.13.1 test
            sbt "coverage;
                 coverageReport;
                 coverageAggregate"
            if [ -z "$CODACY_PROJECT_TOKEN" ]; then
              echo "CODACY_PROJECT_TOKEN not found. Skipping send coverage to Codacy."
            else
              sbt codacyCoverage
            fi
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_sonatype
          context: CodacyAWS
          cmd: |
            sbt "retrieveGPGKeys;+publishSigned;sonatypeReleaseAll"
          requires:
            - compile_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_sonatype
