version: 2.1

orbs:
  codacy: codacy/base@10.8.0

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: compile_test
          cmd: |
            sbt scalafmtSbtCheck scalafmtCheckAll
            sbt +test
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish
          context: CodacyAWS
          cmd: sbt retrieveGPGKeys +publishSigned sonatypeBundleRelease
          requires:
            - compile_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish
